---
title: "Method"
---

The project will deploy multiple regression model using student achievements (SAT Exam scores) as dependent variables. Independent variables include three important indicators of teacher's quality including % of teachers at school with experiences of more than three years, % of positive rating of rigorous instruction, and % of positive rating of teacher's collaborativeness. This multiple regression models will also control for socioeconomic characteristics that are confounders affecting both student achievement and teacher quality. The cofounders controlled in this model are level of poverty as measured by the Economic Need Index and % of positive rating of support provided by schools. Economic status can potentially be a cofounder because students whose families are poor cannot afford to attend, say, private schools where teachers may have better qualifications. At the same time, students from poorer families may not have enough resources to assist their learning and may spend time helping their parents (e.g. take care of their siblings while their parents are out for work). As a result, this can also affect their scores. As for the second cofounder controlled in this study, a supportive school environment can well assist teachers to maximize their teaching capabilities and students learning capabilities. Teachers are able to pull different resources to realise their teaching and students will have learning materials and tools to facilitate their study.

My hypothesis for this project is that better teacher quality will have a positive impact on student's achievements as teachers who have more experience in the field who are also more collaborative and able to give student rigorous instruction will help student improve the comprehension of the learning materials as well as use more efficient way to study.